
#!/bin/bash


VERTICAL_SOLID="│"
VERTICAL_SELECT_SOLID="┊"
HORIZONTAL_SOLID="─"
TITULO_LEFT_SOLID="┤"
TITULO_RIGHT_SOLID="├"
UP_LEFT_SOLID="┌"
UP_RIGHT_SOLID="┐"
BOTTOM_LEFT_SOLID="└"
BOTTOM_RIGHT_SOLID="┘"


VERTICAL_DOTTED="┊"
VERTICAL_SELECT_DOTTED="│"
HORIZONTAL_DOTTED="╌"
TITULO_LEFT_DOTTED="┤"
TITULO_RIGHT_DOTTED="├"
UP_LEFT_DOTTED="┌"
UP_RIGHT_DOTTED="┐"
BOTTOM_LEFT_DOTTED="└"
BOTTOM_RIGHT_DOTTED="┘"

menutheme_shape_names=(
    "solid"
    "dotted"
  )
menutheme_shape_n="${#menutheme_shape_names[@]}"

menutheme_shape_set() {
  eval "menutheme_shape_$1"
}

menutheme_shape_solid() {
  VERTICAL=$VERTICAL_SOLID 
  VERTICAL_SELECT=$VERTICAL_SELECT_SOLID 
  HORIZONTAL=$HORIZONTAL_SOLID
  TITULO_LEFT=$TITULO_LEFT_SOLID
  TITULO_RIGHT=$TITULO_RIGHT_SOLID
  UP_LEFT=$UP_LEFT_SOLID
  UP_RIGHT=$UP_RIGHT_SOLID
  BOTTOM_LEFT=$BOTTOM_LEFT_SOLID
  BOTTOM_RIGHT=$BOTTOM_RIGHT_SOLID
}

menutheme_shape_dotted() {
  VERTICAL=$VERTICAL_DOTTED 
  VERTICAL_SELECT=$VERTICAL_SELECT_DOTTED
  HORIZONTAL=$HORIZONTAL_DOTTED
  TITULO_LEFT=$TITULO_LEFT_DOTTED
  TITULO_RIGHT=$TITULO_RIGHT_DOTTED
  UP_LEFT=$UP_LEFT_DOTTED
  UP_RIGHT=$UP_RIGHT_DOTTED
  BOTTOM_LEFT=$BOTTOM_LEFT_DOTTED
  BOTTOM_RIGHT=$BOTTOM_RIGHT_DOTTED
}
